name: build

on:
  push:
    branches:
    - master
    - development

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: robindebruin/wartemis-planet-wars
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
